# -*- coding: utf-8 -*-
"""harry potter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctud-u_EItgnnDMSfrU0tQKec8zEBJ4s
"""

with open("harry_potter.txt",'r') as f:
  disney= f.read()

disney

splitted_data=disney.split("\n")

splitted_data

title=splitted_data[0]

title

author=splitted_data[-1]

author

titleYear=splitted_data[1:-1]

titleYear

d={}
i=0
for i in range(len(titleYear)):
  dkey=title +' '+str(i+1)
  d[dkey]=None

d

titleList=[]
yearList=[]
for i in titleYear:
  # print(i.split('('))
  title = i.split('(')[0].strip()
  titleList.append(title)
  year = i.split('(')[1][:-1]
  yearList.append(year)
print(titleList)
print(yearList)

i=0
for key in d:
  d[key] = {"title" : titleList[i], "year":yearList[i], "author":author}
  i+=1
d



1